package hibernate;
// Generated 18/11/2018 05:40:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exchanges generated by hbm2java
 */
public class Exchanges  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String exchangeName;
     private float maxAmount;
     private String limitDate;
     private String exchangeDate;
     private String exchangeDescription;
     private String accessCode;
     private Set<ParticipantList> participantLists = new HashSet<ParticipantList>(0);
     private Set<Themes> themeses = new HashSet<Themes>(0);
     private Set<Pairs> pairses = new HashSet<Pairs>(0);

    public Exchanges() {
    }

	
    public Exchanges(Users users, String exchangeName, float maxAmount, String limitDate, String exchangeDate, String exchangeDescription, String accessCode) {
        this.users = users;
        this.exchangeName = exchangeName;
        this.maxAmount = maxAmount;
        this.limitDate = limitDate;
        this.exchangeDate = exchangeDate;
        this.exchangeDescription = exchangeDescription;
        this.accessCode = accessCode;
    }
    public Exchanges(Users users, String exchangeName, float maxAmount, String limitDate, String exchangeDate, String exchangeDescription, String accessCode, Set<ParticipantList> participantLists, Set<Themes> themeses, Set<Pairs> pairses) {
       this.users = users;
       this.exchangeName = exchangeName;
       this.maxAmount = maxAmount;
       this.limitDate = limitDate;
       this.exchangeDate = exchangeDate;
       this.exchangeDescription = exchangeDescription;
       this.accessCode = accessCode;
       this.participantLists = participantLists;
       this.themeses = themeses;
       this.pairses = pairses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getExchangeName() {
        return this.exchangeName;
    }
    
    public void setExchangeName(String exchangeName) {
        this.exchangeName = exchangeName;
    }
    public float getMaxAmount() {
        return this.maxAmount;
    }
    
    public void setMaxAmount(float maxAmount) {
        this.maxAmount = maxAmount;
    }
    public String getLimitDate() {
        return this.limitDate;
    }
    
    public void setLimitDate(String limitDate) {
        this.limitDate = limitDate;
    }
    public String getExchangeDate() {
        return this.exchangeDate;
    }
    
    public void setExchangeDate(String exchangeDate) {
        this.exchangeDate = exchangeDate;
    }
    public String getExchangeDescription() {
        return this.exchangeDescription;
    }
    
    public void setExchangeDescription(String exchangeDescription) {
        this.exchangeDescription = exchangeDescription;
    }
    public String getAccessCode() {
        return this.accessCode;
    }
    
    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode;
    }
    public Set<ParticipantList> getParticipantLists() {
        return this.participantLists;
    }
    
    public void setParticipantLists(Set<ParticipantList> participantLists) {
        this.participantLists = participantLists;
    }
    public Set<Themes> getThemeses() {
        return this.themeses;
    }
    
    public void setThemeses(Set<Themes> themeses) {
        this.themeses = themeses;
    }
    public Set<Pairs> getPairses() {
        return this.pairses;
    }
    
    public void setPairses(Set<Pairs> pairses) {
        this.pairses = pairses;
    }




}


