package hibernate;
// Generated 18/11/2018 05:40:19 PM by Hibernate Tools 4.3.1



/**
 * Pairs generated by hbm2java
 */
public class Pairs  implements java.io.Serializable {


     private Integer id;
     private Exchanges exchanges;
     private Users users;
     private int idUser2;

    public Pairs() {
    }

    public Pairs(Exchanges exchanges, Users users, int idUser2) {
       this.exchanges = exchanges;
       this.users = users;
       this.idUser2 = idUser2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Exchanges getExchanges() {
        return this.exchanges;
    }
    
    public void setExchanges(Exchanges exchanges) {
        this.exchanges = exchanges;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getIdUser2() {
        return this.idUser2;
    }
    
    public void setIdUser2(int idUser2) {
        this.idUser2 = idUser2;
    }




}


