package hibernate;
// Generated 18/11/2018 05:40:19 PM by Hibernate Tools 4.3.1



/**
 * ParticipantList generated by hbm2java
 */
public class ParticipantList  implements java.io.Serializable {


     private Integer id;
     private Exchanges exchanges;
     private Users users;
     private boolean acceptInvite;
     private boolean isInGroup;

    public ParticipantList() {
    }

    public ParticipantList(Exchanges exchanges, Users users, boolean acceptInvite, boolean isInGroup) {
       this.exchanges = exchanges;
       this.users = users;
       this.acceptInvite = acceptInvite;
       this.isInGroup = isInGroup;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Exchanges getExchanges() {
        return this.exchanges;
    }
    
    public void setExchanges(Exchanges exchanges) {
        this.exchanges = exchanges;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public boolean isAcceptInvite() {
        return this.acceptInvite;
    }
    
    public void setAcceptInvite(boolean acceptInvite) {
        this.acceptInvite = acceptInvite;
    }
    public boolean isIsInGroup() {
        return this.isInGroup;
    }
    
    public void setIsInGroup(boolean isInGroup) {
        this.isInGroup = isInGroup;
    }




}


