package hibernate;
// Generated 18/11/2018 05:40:19 PM by Hibernate Tools 4.3.1



/**
 * Themes generated by hbm2java
 */
public class Themes  implements java.io.Serializable {


     private Integer id;
     private Exchanges exchanges;
     private String themeName;

    public Themes() {
    }

    public Themes(Exchanges exchanges, String themeName) {
       this.exchanges = exchanges;
       this.themeName = themeName;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Exchanges getExchanges() {
        return this.exchanges;
    }
    
    public void setExchanges(Exchanges exchanges) {
        this.exchanges = exchanges;
    }
    public String getThemeName() {
        return this.themeName;
    }
    
    public void setThemeName(String themeName) {
        this.themeName = themeName;
    }




}


